[package]
name = "snail"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
clap = { version = "4", features = ["derive"] }
pest = "2.7"
pest_derive = "2.7"
pyo3 = { version = "0.21", features = ["auto-initialize"] }

[dev-dependencies]
tempfile = "3"
