[workspace]
resolver = "2"
members = [
    "crates/snail-ast",
    "crates/snail-error",
    "crates/snail-parser",
    "crates/snail-python",
]

[workspace.package]
edition = "2024"

[workspace.lints.rust]
warnings = "deny"

[workspace.lints.clippy]
all = "deny"
