[workspace]
resolver = "2"
members = [
    "crates/snail-ast",
    "crates/snail-python-ast",
    "crates/snail-error",
    "crates/snail-parser",
    "crates/snail-lower",
    "snail",
]

[workspace.package]
edition = "2024"
