[package]
name = "snail-lower"
version = "0.3.4"
edition = "2024"

[dependencies]
snail-ast = { path = "../snail-ast" }
snail-python-ast = { path = "../snail-python-ast" }
snail-error = { path = "../snail-error" }
