[package]
name = "snail-lower"
version = "0.5.1"
edition = "2024"

[dependencies]
snail-ast = { path = "../snail-ast" }
snail-error = { path = "../snail-error" }
pyo3 = { version = "0.21", features = ["abi3-py310"] }
