[package]
name = "snail-python"
version = "0.3.3"
edition.workspace = true

[lib]
name = "snail_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module", "abi3-py310"] }
snail-core = { path = "../snail-core" }
